### ISSUE TITLE
bug: App crashing everytime we tap 'About' > 'Open source licenses'

### ISSUE THREAD

**Issue by cyberboh** [ReVanced/revanced-manager#2562]
### Bug description

It crashing in 'Open source licenses' section.

### Version of ReVanced Manager and version & name of app you are patching

0.0.1 
Latest commit https://github.com/ReVanced/revanced-manager/commit/7338157e2798cd9b824bc408d7beccbf5a3add43

### Installation method

None

### ReVanced Manager logs

```shell
--------- beginning of crash
05-22 11:53:23.012 30667 30667 E AndroidRuntime: FATAL EXCEPTION: main
05-22 11:53:23.012 30667 30667 E AndroidRuntime: Process: app.revanced.manager, PID: 30667
05-22 11:53:23.012 30667 30667 E AndroidRuntime: java.lang.NoSuchMethodError: No static method FlowRow(Landroidx/compose/ui/Modifier;Landroidx/compose/foundation/layout/Arrangement$Horizontal;Landroidx/compose/foundation/layout/Arrangement$Vertical;IILandroidx/compose/foundation/layout/FlowRowOverflow;Lkotlin/jvm/functions/Function3;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/foundation/layout/FlowLayoutKt; or its super classes (declaration of 'androidx.compose.foundation.layout.FlowLayoutKt' appears in /data/app/~~CXeaGZBJtlrgwov0gnlXMg==/app.revanced.manager-xsIfjnF8EVx8wDKMeGio7A==/base.apk)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at coil.util.-Collections.Library(Unknown Source:735)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at com.mikepenz.aboutlibraries.ui.compose.SharedLibrariesKt$Libraries_ajgufuY$lambda$11$lambda$10$$inlined$libraryItems$1.invoke(Unknown Source:116)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:42)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:3)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListItemProviderImpl$Item$1.invoke(Unknown Source:135)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:25)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:1)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.AnchoredGroupPath.CompositionLocalProvider(SourceFile:77)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazyLayoutKt.LazyLayoutPinnableItem(Unknown Source:237)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListItemProviderImpl.Item(Unknown Source:28)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.material3.TabKt$TabBaselineLayout$3.invoke(Unknown Source:321)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:25)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:1)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.AnchoredGroupPath.CompositionLocalProvider(SourceFile:77)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(Unknown Source:95)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazySaveableStateHolder.SaveableStateProvider(Unknown Source:12)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazyLayoutKt.access$SkippableItem-JVlU9Rs(Unknown Source:106)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(Unknown Source:1211)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:25)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:1)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(Unknown Source:542)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:25)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(SourceFile:1)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.internal.Utils_jvmKt.invokeComposable(Unknown Source:17)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl.doCompose-aFTiNEg(Unknown Source:79)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.composeContent(Unknown Source:34)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Unknown Source:42)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Unknown Source:4)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Unknown Source:4)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.CompositionImpl.composeInitial(Unknown Source:11)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcomposeInto(Unknown Source:27)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(Unknown Source:118)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(Unknown Source:166)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.measure-0kLqBqw(Unknown Source:29)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1$measuredItemProvider$1.getAndMeasure-0kLqBqw(Unknown Source:18)
05-22 11:53:23.012 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.lazy.LazyListKt$rememberLazyListMeasurePolicy$1$1.invoke(Unknown Source:689)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.CanvasKt$Canvas$1.invoke(Unknown Source:1113)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$createMeasurePolicy$1.measure-3p2s80s(Unknown Source:70)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:37)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.graphics.SimpleGraphicsLayerModifier.measure-3p2s80s(Unknown Source:0)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.lazy.layout.LazyLayoutBeyondBoundsModifierNode.measure-3p2s80s(Unknown Source:0)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.foundation.layout.FillNode.measure-3p2s80s(Unknown Source:104)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasurePassDelegate$layoutChildrenBlock$1.invoke(Unknown Source:128)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotId_jvmKt.observe(Unknown Source:50)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:55)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:123)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:119)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(Unknown Source:17)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(Unknown Source:17)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(Unknown Source:7)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(Unknown Source:144)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(Unknown Source:99)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(Unknown Source:113)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(Unknown Source:113)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtree(Unknown Source:27)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.forceMeasureTheSubtree(Unknown Source:2)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:58)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasurePassDelegate.measure-BRTryo0(Unknown Source:98)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.animation.AnimatedEnterExitMeasurePolicy.measure-3p2s80s(Unknown Source:24)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.InnerNodeCoordinator.measure-BRTryo0(Unknown Source:37)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.animation.EnterExitTransitionModifierNode.measure-3p2s80s(Unknown Source:191)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.graphics.BlockGraphicsLayerModifier.measure-3p2s80s(Unknown Source:0)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutKt$materializerOf$1.invoke(Unknown Source:1311)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.layout.LayoutModifierImpl.measure-3p2s80s(Unknown Source:7)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutModifierNodeCoordinator.measure-BRTryo0(Unknown Source:10)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasurePassDelegate$layoutChildrenBlock$1.invoke(Unknown Source:128)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotId_jvmKt.observe(Unknown Source:108)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(Unknown Source:55)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(Unknown Source:123)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(Unknown Source:2)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:119)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(Unknown Source:17)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release$default(Unknown Source:17)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(Unknown Source:7)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureAndRelayoutIfNeeded(Unknown Source:144)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(Unknown Source:99)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtreeInternal(Unknown Source:113)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.forceMeasureTheSubtree(Unknown Source:27)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.forceMeasureTheSubtree(Unknown Source:2)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasurePassDelegate.remeasure-BRTryo0(Unknown Source:58)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.LayoutNode.remeasure-_Sx5XlM$ui_release(Unknown Source:17)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.doRemeasure-sdFAvZA(Unknown Source:2)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.remeasureOnly(Unknown Source:22)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.node.MeasureAndLayoutDelegate.measureOnly(Unknown Source:78)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.onMeasure(Unknown Source:98)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.View.measure(View.java:29584)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView.internalOnMeasure$ui_release(Unknown Source:63)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at androidx.compose.ui.platform.AbstractComposeView.onMeasure(Unknown Source:3)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.View.measure(View.java:29584)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7145)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.View.measure(View.java:29584)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7145)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.View.measure(View.java:29584)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7145)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:801)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.View.measure(View.java:29584)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:5558)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3866)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4204)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3549)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11736)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1778)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1787)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1279)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:1155)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1746)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:249)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:337)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:9465)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:636)
05-22 11:53:23.013 30667 30667 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1005)
```

### Patch logs

```shell
None
```

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] The bug is only related to ReVanced Manager.

**Comment by Brosssh** [comment]
This is a bug introduced with https://github.com/ReVanced/revanced-manager/commit/e71e6fb7973dea6fb60c5b738d3d37276a403f88 by bumping `compose-bom = "2025.05.00"`. Reverting it to `"2025.01.01"` fixed the issue. 

@Axelen123 do you know if it's a compose bug or if we are doing something wrong? I found out [this](https://community.intercom.com/mobile-sdks-24/java-lang-nosuchmethoderror-no-static-method-flowrow-9891), but they are saying `"2025.05.00"` fixed the issue while for us it's not.
